<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HP-ENVY" failures="1" tests="10" name="org.automation.ui.BlazeDemoTests" time="379.580" errors="0" timestamp="2025-09-25T08:58:44 IST" skipped="0">
  <testcase classname="org.automation.ui.BlazeDemoTests" name="testFlightSelectionPage" time="34.641"/>
  <testcase classname="org.automation.ui.BlazeDemoTests" name="testPurchasePageContainsForm" time="42.053"/>
  <testcase classname="org.automation.ui.BlazeDemoTests" name="testHomePageContainsDepartureAndDestination" time="36.098"/>
  <testcase classname="org.automation.ui.BlazeDemoTests" name="testConfirmationPage" time="36.258">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at org.automation.ui.BlazeDemoTests.testConfirmationPage(BlazeDemoTests.java:91)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
  </testcase> <!-- testConfirmationPage -->
  <testcase classname="org.automation.ui.BlazeDemoTests" name="testHomePageTitle" time="33.760"/>
  <testcase classname="org.automation.ui.BlazeDemoTests" name="testNavigateToHomePage" time="33.456"/>
  <testcase classname="org.automation.ui.BlazeDemoTests" name="testPurchaseFlight" time="44.383"/>
  <testcase classname="org.automation.ui.BlazeDemoTests" name="testFlightSearchNavigation" time="39.786"/>
  <testcase classname="org.automation.ui.BlazeDemoTests" name="testSelectFirstFlight" time="40.457"/>
  <testcase classname="org.automation.ui.BlazeDemoTests" name="testFillPurchaseForm" time="38.688"/>
</testsuite> <!-- org.automation.ui.BlazeDemoTests -->
